# Generated by Django 6.0.6 on 2026-06-08 09:50

import django.db.models.deletion
from django.db import migrations, models

def migrate_strings_to_fks(apps, schema_editor):
    Student = apps.get_model('students', 'Student')
    Department = apps.get_model('courses', 'Department')
    Semester = apps.get_model('courses', 'Semester')
    
    for student in Student.objects.all():
        dept = Department.objects.filter(name__iexact=student.department).first()
        if not dept:
            dept = Department.objects.first()
            
        sem = Semester.objects.filter(name__iexact=student.semester).first()
        if not sem:
            sem = Semester.objects.first()
            
        student.department = str(dept.id) if dept else "1"
        student.semester = str(sem.id) if sem else "1"
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_course_department_remove_course_semester_and_more'),
        ('students', '0003_alter_student_name_rename_name_student_full_name_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_strings_to_fks, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='courses.semester'),
        ),
    ]

