# Generated by Django 6.0.6 on 2026-06-08 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_assigned_by_enrollment_assignment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='assignment_type',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_type',
            field=models.CharField(choices=[('CURRICULUM', 'Curriculum'), ('MANUAL', 'Manual')], default='CURRICULUM', max_length=15),
        ),
        migrations.AddField(
            model_name='semester',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='courses.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='courses.semester')),
            ],
            options={
                'unique_together': {('department', 'semester')},
            },
        ),
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='courses.course')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_courses', to='courses.curriculum')),
            ],
            options={
                'unique_together': {('curriculum', 'course')},
            },
        ),
    ]
